version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: schools_db
      POSTGRES_USER: schools_user
      POSTGRES_PASSWORD: schools_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      DATABASE_URL: postgresql://schools_user:schools_password@db/schools_db
    depends_on:
      - db

  data_mapper:
    build:
      context: .
      dockerfile: Dockerfile.mapper
    environment:
      DATABASE_URL: postgresql://schools_user:schools_password@db/schools_db
    depends_on:
      - db
    volumes:
      - ./schools.csv:/app/schools.csv

volumes:
  postgres_data:
