version: '3.8'

services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_DB: schools_db
      POSTGRES_USER: schools_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-schoolspass}
    ports:
      - "5432:5432"
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      POSTGRES_DB: schools_db
      POSTGRES_USER: schools_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-schoolspass}
    depends_on:
      - db

  data_mapper:
    build:
      context: .
      dockerfile: Dockerfile.mapper
    environment:
      POSTGRES_DB: schools_db
      POSTGRES_USER: schools_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-schoolspass}
    depends_on:
      - db
    volumes:
      - ./schools.csv:/app/schools.csv:ro

volumes:
  postgres_data:
