name: Build and Deploy to GCP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCE_INSTANCE: ${{ secrets.GCE_INSTANCE }}
  GCE_INSTANCE_ZONE: ${{ secrets.GCE_INSTANCE_ZONE }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Configure Docker to use GCP credentials
      run: |
        gcloud auth configure-docker

    - name: Copy files to GCP instance
      run: |
        gcloud compute scp --zone=${{ secrets.GCE_INSTANCE_ZONE }} --recurse ./* ${{ secrets.GCE_INSTANCE }}:~/app/
        
    - name: Deploy to GCP VM
      run: |
        gcloud compute ssh --zone=${{ secrets.GCE_INSTANCE_ZONE }} ${{ secrets.GCE_INSTANCE }} --command='
          cd ~/app && 
          docker-compose down &&
          docker-compose pull &&
          docker-compose up -d
        '
