name: Respond to Issues
on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  respond:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: dkpoulsen/huggingchat-action@v0.0.4
        with:
          huggingface_email: ${{ secrets.HUGCHAT_EMAIL }}
          huggingface_password: ${{ secrets.HUGCHAT_PASSWORD }}