name: Respond to Issues
on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  respond:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: dkpoulsen/huggingchat-action@v0.0.6
        with:
          huggingface_email: ${{ secrets.HUGCHAT_EMAIL }}
          huggingface_password: ${{ secrets.HUGCHAT_PASSWORD }}
          assistant_id: '65c7076dc81caf6fe37d6165'
